name: flutter_map_location_marker
description: A flutter map plugin for displaying device current location.
version: 5.0.0+1
repository: https://github.com/tlserver/flutter_map_location_marker

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_compass: ^0.7.0
  flutter_map: ^3.0.0
  geolocator: ^9.0.1
  latlong2: ^0.8.1

dev_dependencies:
  flutter_joystick: ^0.0.2
  flutter_test:
    sdk: flutter
  lint: ^1.10.0

flutter:
